name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'lib/**'
      - 'test/**'
      - '.github/**'
      - 'Rakefile'
  pull_request:
    branches: ['**']
    paths:
      - 'lib/**'
      - 'test/**'
      - '.github/**'
      - 'Rakefile'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.4', '2.7', head, jruby ]
	# ruby: [ '2.4', '2.7', head, jruby, truffleruby ]
	# truffleruby has https://github.com/oracle/truffleruby/issues/2631
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Run tests
        run: rake test
